version: "3"
services:
  automated-browser-tests:
    build:
      context: .
    environment:
      - TAG=${TAG}
    volumes:
      - ./:/e2e
      - ./package.json:/e2e/package.json
      - ./package-lock.json:/e2e/package-lock.json
